version: '3.7'
services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    hostname: sabnzbd
    restart: unless-stopped
    volumes:
      - ../Config/sabnzbd.ini:/config/sabnzbd.ini
      - ../Data/config:/config
      - ../Data/downloads:/downloads
      - ../Data/incomplete-downloads:/incomplete-downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.sabnzbd.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.sabnzbd.entrypoints=web-secure"
      - "traefik.http.routers.sabnzbd.middlewares=default-headers@file"
      - "traefik.http.routers.sabnzbd.service=sabnzbd"
      - "traefik.http.routers.sabnzbd.tls=true"
      - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080" # Proxied Port
